spring:
  application:
    name: account
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8060
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: busrefresh