spring:
  application:
    name: card
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8060
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: busrefresh