spring:
  application:
    name: loan
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8060

management:
  endpoints:
    web:
      exposure:
        include: refresh