spring:
  application:
    name: message
  cloud:
    function:
      definition: fetchAccountMessage|fetchAccountNumber
    stream:
      bindings:
        fetchAccountMessagefetchAccountNumber-in-0:
          destination: account-message
          group: ${spring.application.name}
        fetchAccountMessagefetchAccountNumber-out-0:
          destination: acknowledgement-message
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s

server:
  port: 8030

